import type {
  PortfolioRevisionRoute,
  PortfolioWorkflowStatus,
  StudentCategory,
} from "@/types/database";
import {
  getPortfolioWorkflowSemanticIntent,
  isPortfolioWorkflowStatus,
} from "@/lib/status/status-intent";

export type PortfolioWorkflowPresentation = {
  title: string;
  description: string;
};

export {
  getPortfolioWorkflowSemanticIntent,
  isPortfolioWorkflowStatus,
};

function lockedDescription(sequenceOrder: number | undefined): string {
  if (sequenceOrder === 2) {
    return "Complete the Photography portfolio before this portfolio begins.";
  }
  if (sequenceOrder === 3) {
    return "Complete the Makeup portfolio before this portfolio begins.";
  }
  return "Complete the previous portfolio before this portfolio begins.";
}

export function getPortfolioWorkflowPresentation(
  workflowStatus: PortfolioWorkflowStatus,
  portfolioType: StudentCategory,
  options: {
    revisionReturnTo?: PortfolioRevisionRoute | null;
    sequenceOrder?: number;
  } = {}
): PortfolioWorkflowPresentation {
  switch (workflowStatus) {
    case "locked":
      return {
        title: "Locked",
        description: lockedDescription(options.sequenceOrder),
      };
    case "awaiting_booking":
      return {
        title: "Ready for studio booking",
        description: "Book the studio before submitting your portfolio.",
      };
    case "awaiting_studio_checkin":
      return {
        title: "Enter the studio OTP",
        description:
          "Your studio booking is confirmed. Enter the real-time OTP generated by Admin to unlock portfolio submission.",
      };
    case "awaiting_submission":
      return {
        title: "Ready for portfolio submission",
        description:
          "Physical check-in is complete. Submit your portfolio link from this account.",
      };
    case "pending_educator":
      return {
        title: "Portfolio under Admin review",
        description:
          "Your submission is with IncluHub Admin. Educator comments are advisory.",
      };
    case "pending_admin":
      return {
        title: "Portfolio under Admin review",
        description: "Awaiting IncluHub Admin's decision.",
      };
    case "revision_required":
      if (options.revisionReturnTo === "admin") {
        return {
          title: "Revision requested by Admin",
          description:
            "Read the Admin feedback and resubmit a new portfolio version.",
        };
      }
      return {
        title: "Revision requested by Admin",
        description:
          "Read the Admin feedback and resubmit a new portfolio version.",
      };
    case "completed":
      return {
        title: "Portfolio approved",
        description: "IncluHub Admin approval completed.",
      };
    default: {
      const _exhaustive: never = workflowStatus;
      return _exhaustive;
    }
  }
}

export function shouldShowSubmittedPortfolioSummary(
  workflowStatus: PortfolioWorkflowStatus
): boolean {
  return (
    workflowStatus === "pending_educator" ||
    workflowStatus === "pending_admin" ||
    workflowStatus === "revision_required" ||
    workflowStatus === "completed"
  );
}

export function findActiveTeamPortfolio<
  T extends { sequenceOrder: number; workflowStatus: PortfolioWorkflowStatus }
>(portfolios: T[]): T | null {
  const sorted = portfolios.slice().sort((a, b) => a.sequenceOrder - b.sequenceOrder);
  return sorted.find((portfolio) => portfolio.workflowStatus !== "completed") ?? null;
}
